{{- if .Values.detection.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.detection.connectionName }}
  labels:
    {{- include "zoom-enhance.labels" . | nindent 4 }}
    opendatahub.io/dashboard: "true"
  annotations:
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/display-name: {{ .Values.detection.connectionName }}
type: Opaque
data:
  URI: {{ printf "oci://%s:%s" .Values.detection.image.repository .Values.detection.image.tag | b64enc }}
{{- end }}
