{{- if .Values.pipelines.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-dspa-secret
  labels:
    {{- include "caisat.labels" . | nindent 4 }}
    app.kubernetes.io/component: pipelines
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s4.credentials.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s4.credentials.secretKey }}
{{- end }}
