{{- if .Values.pipelines.runAnalysis }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "caisat.fullname" . }}-pipeline-runner
  labels:
    {{- include "caisat.labels" . | nindent 4 }}
    app.kubernetes.io/component: pipeline
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "8"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "caisat.fullname" . }}-pipeline-runner-edit
  labels:
    {{- include "caisat.labels" . | nindent 4 }}
    app.kubernetes.io/component: pipeline
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "8"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ include "caisat.fullname" . }}-pipeline-runner
    namespace: {{ .Release.Namespace }}
{{- end }}
