{{- if .Values.s4.seed.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "caisat.fullname" . }}-s4-seed
  labels:
    {{- include "caisat.labels" . | nindent 4 }}
    app.kubernetes.io/component: s4-seed

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "caisat.fullname" . }}-s4-seed-view
  labels:
    {{- include "caisat.labels" . | nindent 4 }}
    app.kubernetes.io/component: s4-seed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: {{ include "caisat.fullname" . }}-s4-seed
  namespace: {{ .Release.Namespace }}
{{- end }}
